name: Django Blog CI/CD

on:
  push:
    branches: [ main ] # Uruchamia się przy wrzucaniu na main
  pull_request:
    branches: [ main ] # Uruchamia się przy robieniu Pull Requesta

jobs:
  # JOB 1: Testowanie (zawsze)
  tests:
    runs-on: ubuntu-latest
    services:
     
      db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r ./baked_blog-main/requirements.txt
         

      - name: Run Django Tests
        run: python ./baked_blog-main/manage.py test
        env:
          DB_HOST: 127.0.0.1
          DB_NAME: test_db
          DB_USER: root
          DB_PASSWORD: root_password

  # JOB 2: Budowanie i Push (tylko na MAIN)
  build-and-push:
    needs: tests 
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Logowanie do DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: my-docker-hub-namespace/my-docker-hub-repository

      
      - name: Budowanie i push do Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ../../baked_blog-main/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
